//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:DefaultNamespace", ConfigurationName="ServiceReference.ServicoFornecedores")]
    public interface ServicoFornecedores
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="EsqueciMinhaSenha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.EsqueciMinhaSenhaResponse> EsqueciMinhaSenhaAsync(ServiceReference.EsqueciMinhaSenhaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="InserirFornecedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.InserirFornecedorResponse> InserirFornecedorAsync(ServiceReference.InserirFornecedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlterarSenha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.AlterarSenhaResponse> AlterarSenhaAsync(ServiceReference.AlterarSenhaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlterarSenhaSemSenhaAtual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.AlterarSenhaSemSenhaAtualResponse> AlterarSenhaSemSenhaAtualAsync(ServiceReference.AlterarSenhaSemSenhaAtualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Autentica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.AutenticaResponse> AutenticaAsync(ServiceReference.AutenticaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RetornarQuantidadeTotalFornecedores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.RetornarQuantidadeTotalFornecedoresResponse> RetornarQuantidadeTotalFornecedoresAsync(ServiceReference.RetornarQuantidadeTotalFornecedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RetornarUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.RetornarUsuariosResponse> RetornarUsuariosAsync(ServiceReference.RetornarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RetornarUsuarioPorCNPJ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.RetornarUsuarioPorCNPJResponse> RetornarUsuarioPorCNPJAsync(ServiceReference.RetornarUsuarioPorCNPJRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RetornarCRCPorCNPJ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.RetornarCRCPorCNPJResponse> RetornarCRCPorCNPJAsync(ServiceReference.RetornarCRCPorCNPJRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class ResultadoEsqueceSenha
    {
        
        private bool alterouField;
        
        private string novaSenhaField;
        
        private string erroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Alterou
        {
            get
            {
                return this.alterouField;
            }
            set
            {
                this.alterouField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string NovaSenha
        {
            get
            {
                return this.novaSenhaField;
            }
            set
            {
                this.novaSenhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class CRC
    {
        
        private string numeroCRCField;
        
        private string nomeFornecedorField;
        
        private string logradouroFornecedorField;
        
        private string numeroLogradouroFornecedorField;
        
        private string complementoLogradouroFornecedorField;
        
        private string bairroFornecedorField;
        
        private string cEPFornecedorField;
        
        private string cidadeFornecedorField;
        
        private string estadoFornecedorField;
        
        private string cNPJForncedorField;
        
        private string tipoFornecedorField;
        
        private string dataEmissaoCRCField;
        
        private string validadeCRCField;
        
        private string anoUltimoBalancoField;
        
        private string[] codigosCategoriasComerciaisField;
        
        private string[] descricoesCategoriasComerciaisField;
        
        private string erroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string NumeroCRC
        {
            get
            {
                return this.numeroCRCField;
            }
            set
            {
                this.numeroCRCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string NomeFornecedor
        {
            get
            {
                return this.nomeFornecedorField;
            }
            set
            {
                this.nomeFornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string LogradouroFornecedor
        {
            get
            {
                return this.logradouroFornecedorField;
            }
            set
            {
                this.logradouroFornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string NumeroLogradouroFornecedor
        {
            get
            {
                return this.numeroLogradouroFornecedorField;
            }
            set
            {
                this.numeroLogradouroFornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string ComplementoLogradouroFornecedor
        {
            get
            {
                return this.complementoLogradouroFornecedorField;
            }
            set
            {
                this.complementoLogradouroFornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string BairroFornecedor
        {
            get
            {
                return this.bairroFornecedorField;
            }
            set
            {
                this.bairroFornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string CEPFornecedor
        {
            get
            {
                return this.cEPFornecedorField;
            }
            set
            {
                this.cEPFornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string CidadeFornecedor
        {
            get
            {
                return this.cidadeFornecedorField;
            }
            set
            {
                this.cidadeFornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string EstadoFornecedor
        {
            get
            {
                return this.estadoFornecedorField;
            }
            set
            {
                this.estadoFornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string CNPJForncedor
        {
            get
            {
                return this.cNPJForncedorField;
            }
            set
            {
                this.cNPJForncedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string TipoFornecedor
        {
            get
            {
                return this.tipoFornecedorField;
            }
            set
            {
                this.tipoFornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string DataEmissaoCRC
        {
            get
            {
                return this.dataEmissaoCRCField;
            }
            set
            {
                this.dataEmissaoCRCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string ValidadeCRC
        {
            get
            {
                return this.validadeCRCField;
            }
            set
            {
                this.validadeCRCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string AnoUltimoBalanco
        {
            get
            {
                return this.anoUltimoBalancoField;
            }
            set
            {
                this.anoUltimoBalancoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codigosCategoriasComerciais", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string[] codigosCategoriasComerciais
        {
            get
            {
                return this.codigosCategoriasComerciaisField;
            }
            set
            {
                this.codigosCategoriasComerciaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descricoesCategoriasComerciais", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string[] descricoesCategoriasComerciais
        {
            get
            {
                return this.descricoesCategoriasComerciaisField;
            }
            set
            {
                this.descricoesCategoriasComerciaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class Usuario
    {
        
        private string loginField;
        
        private string emailField;
        
        private string cNPJField;
        
        private string senhaField;
        
        private string nomeField;
        
        private string erroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string CNPJ
        {
            get
            {
                return this.cNPJField;
            }
            set
            {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string Senha
        {
            get
            {
                return this.senhaField;
            }
            set
            {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class ResultadoAlteraSenha
    {
        
        private bool alterouField;
        
        private string erroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool alterou
        {
            get
            {
                return this.alterouField;
            }
            set
            {
                this.alterouField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class ResultadoInserirFornecedor
    {
        
        private bool inseriuField;
        
        private bool temErroField;
        
        private string senhaField;
        
        private string mensagemField;
        
        private string erroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Inseriu
        {
            get
            {
                return this.inseriuField;
            }
            set
            {
                this.inseriuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool TemErro
        {
            get
            {
                return this.temErroField;
            }
            set
            {
                this.temErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Senha
        {
            get
            {
                return this.senhaField;
            }
            set
            {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string Mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsqueciMinhaSenhaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public string login;
        
        public EsqueciMinhaSenhaRequest()
        {
        }
        
        public EsqueciMinhaSenhaRequest(string login)
        {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsqueciMinhaSenhaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public ServiceReference.ResultadoEsqueceSenha EsqueciMinhaSenhaReturn;
        
        public EsqueciMinhaSenhaResponse()
        {
        }
        
        public EsqueciMinhaSenhaResponse(ServiceReference.ResultadoEsqueceSenha EsqueciMinhaSenhaReturn)
        {
            this.EsqueciMinhaSenhaReturn = EsqueciMinhaSenhaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirFornecedorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public string cnpjCpf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=1)]
        public string razaoSocial;
        
        public InserirFornecedorRequest()
        {
        }
        
        public InserirFornecedorRequest(string cnpjCpf, string razaoSocial)
        {
            this.cnpjCpf = cnpjCpf;
            this.razaoSocial = razaoSocial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirFornecedorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public ServiceReference.ResultadoInserirFornecedor InserirFornecedorReturn;
        
        public InserirFornecedorResponse()
        {
        }
        
        public InserirFornecedorResponse(ServiceReference.ResultadoInserirFornecedor InserirFornecedorReturn)
        {
            this.InserirFornecedorReturn = InserirFornecedorReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarSenhaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=1)]
        public string senha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=2)]
        public string novaSenha;
        
        public AlterarSenhaRequest()
        {
        }
        
        public AlterarSenhaRequest(string login, string senha, string novaSenha)
        {
            this.login = login;
            this.senha = senha;
            this.novaSenha = novaSenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarSenhaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public ServiceReference.ResultadoAlteraSenha AlterarSenhaReturn;
        
        public AlterarSenhaResponse()
        {
        }
        
        public AlterarSenhaResponse(ServiceReference.ResultadoAlteraSenha AlterarSenhaReturn)
        {
            this.AlterarSenhaReturn = AlterarSenhaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarSenhaSemSenhaAtualRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=1)]
        public string novaSenha;
        
        public AlterarSenhaSemSenhaAtualRequest()
        {
        }
        
        public AlterarSenhaSemSenhaAtualRequest(string login, string novaSenha)
        {
            this.login = login;
            this.novaSenha = novaSenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarSenhaSemSenhaAtualResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public ServiceReference.ResultadoAlteraSenha AlterarSenhaSemSenhaAtualReturn;
        
        public AlterarSenhaSemSenhaAtualResponse()
        {
        }
        
        public AlterarSenhaSemSenhaAtualResponse(ServiceReference.ResultadoAlteraSenha AlterarSenhaSemSenhaAtualReturn)
        {
            this.AlterarSenhaSemSenhaAtualReturn = AlterarSenhaSemSenhaAtualReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=1)]
        public string senha;
        
        public AutenticaRequest()
        {
        }
        
        public AutenticaRequest(string login, string senha)
        {
            this.login = login;
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public bool AutenticaReturn;
        
        public AutenticaResponse()
        {
        }
        
        public AutenticaResponse(bool AutenticaReturn)
        {
            this.AutenticaReturn = AutenticaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarQuantidadeTotalFornecedoresRequest
    {
        
        public RetornarQuantidadeTotalFornecedoresRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarQuantidadeTotalFornecedoresResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public int RetornarQuantidadeTotalFornecedoresReturn;
        
        public RetornarQuantidadeTotalFornecedoresResponse()
        {
        }
        
        public RetornarQuantidadeTotalFornecedoresResponse(int RetornarQuantidadeTotalFornecedoresReturn)
        {
            this.RetornarQuantidadeTotalFornecedoresReturn = RetornarQuantidadeTotalFornecedoresReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarUsuariosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public int quantidadePorPagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=1)]
        public int pagina;
        
        public RetornarUsuariosRequest()
        {
        }
        
        public RetornarUsuariosRequest(int quantidadePorPagina, int pagina)
        {
            this.quantidadePorPagina = quantidadePorPagina;
            this.pagina = pagina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarUsuariosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ServiceReference.Usuario[] RetornarUsuariosReturn;
        
        public RetornarUsuariosResponse()
        {
        }
        
        public RetornarUsuariosResponse(ServiceReference.Usuario[] RetornarUsuariosReturn)
        {
            this.RetornarUsuariosReturn = RetornarUsuariosReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarUsuarioPorCNPJRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public string cnpj;
        
        public RetornarUsuarioPorCNPJRequest()
        {
        }
        
        public RetornarUsuarioPorCNPJRequest(string cnpj)
        {
            this.cnpj = cnpj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarUsuarioPorCNPJResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public ServiceReference.Usuario RetornarUsuarioPorCNPJReturn;
        
        public RetornarUsuarioPorCNPJResponse()
        {
        }
        
        public RetornarUsuarioPorCNPJResponse(ServiceReference.Usuario RetornarUsuarioPorCNPJReturn)
        {
            this.RetornarUsuarioPorCNPJReturn = RetornarUsuarioPorCNPJReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarCRCPorCNPJRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public string cnpj;
        
        public RetornarCRCPorCNPJRequest()
        {
        }
        
        public RetornarCRCPorCNPJRequest(string cnpj)
        {
            this.cnpj = cnpj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarCRCPorCNPJResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DefaultNamespace", Order=0)]
        public ServiceReference.CRC RetornarCRCPorCNPJReturn;
        
        public RetornarCRCPorCNPJResponse()
        {
        }
        
        public RetornarCRCPorCNPJResponse(ServiceReference.CRC RetornarCRCPorCNPJReturn)
        {
            this.RetornarCRCPorCNPJReturn = RetornarCRCPorCNPJReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface ServicoFornecedoresChannel : ServiceReference.ServicoFornecedores, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ServicoFornecedoresClient : System.ServiceModel.ClientBase<ServiceReference.ServicoFornecedores>, ServiceReference.ServicoFornecedores
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicoFornecedoresClient() : 
                base(ServicoFornecedoresClient.GetDefaultBinding(), ServicoFornecedoresClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Domino.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoFornecedoresClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicoFornecedoresClient.GetBindingForEndpoint(endpointConfiguration), ServicoFornecedoresClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoFornecedoresClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicoFornecedoresClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoFornecedoresClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicoFornecedoresClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoFornecedoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.EsqueciMinhaSenhaResponse> ServiceReference.ServicoFornecedores.EsqueciMinhaSenhaAsync(ServiceReference.EsqueciMinhaSenhaRequest request)
        {
            return base.Channel.EsqueciMinhaSenhaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.EsqueciMinhaSenhaResponse> EsqueciMinhaSenhaAsync(string login)
        {
            ServiceReference.EsqueciMinhaSenhaRequest inValue = new ServiceReference.EsqueciMinhaSenhaRequest();
            inValue.login = login;
            return ((ServiceReference.ServicoFornecedores)(this)).EsqueciMinhaSenhaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.InserirFornecedorResponse> ServiceReference.ServicoFornecedores.InserirFornecedorAsync(ServiceReference.InserirFornecedorRequest request)
        {
            return base.Channel.InserirFornecedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.InserirFornecedorResponse> InserirFornecedorAsync(string cnpjCpf, string razaoSocial)
        {
            ServiceReference.InserirFornecedorRequest inValue = new ServiceReference.InserirFornecedorRequest();
            inValue.cnpjCpf = cnpjCpf;
            inValue.razaoSocial = razaoSocial;
            return ((ServiceReference.ServicoFornecedores)(this)).InserirFornecedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AlterarSenhaResponse> ServiceReference.ServicoFornecedores.AlterarSenhaAsync(ServiceReference.AlterarSenhaRequest request)
        {
            return base.Channel.AlterarSenhaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AlterarSenhaResponse> AlterarSenhaAsync(string login, string senha, string novaSenha)
        {
            ServiceReference.AlterarSenhaRequest inValue = new ServiceReference.AlterarSenhaRequest();
            inValue.login = login;
            inValue.senha = senha;
            inValue.novaSenha = novaSenha;
            return ((ServiceReference.ServicoFornecedores)(this)).AlterarSenhaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AlterarSenhaSemSenhaAtualResponse> ServiceReference.ServicoFornecedores.AlterarSenhaSemSenhaAtualAsync(ServiceReference.AlterarSenhaSemSenhaAtualRequest request)
        {
            return base.Channel.AlterarSenhaSemSenhaAtualAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AlterarSenhaSemSenhaAtualResponse> AlterarSenhaSemSenhaAtualAsync(string login, string novaSenha)
        {
            ServiceReference.AlterarSenhaSemSenhaAtualRequest inValue = new ServiceReference.AlterarSenhaSemSenhaAtualRequest();
            inValue.login = login;
            inValue.novaSenha = novaSenha;
            return ((ServiceReference.ServicoFornecedores)(this)).AlterarSenhaSemSenhaAtualAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AutenticaResponse> ServiceReference.ServicoFornecedores.AutenticaAsync(ServiceReference.AutenticaRequest request)
        {
            return base.Channel.AutenticaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AutenticaResponse> AutenticaAsync(string login, string senha)
        {
            ServiceReference.AutenticaRequest inValue = new ServiceReference.AutenticaRequest();
            inValue.login = login;
            inValue.senha = senha;
            return ((ServiceReference.ServicoFornecedores)(this)).AutenticaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.RetornarQuantidadeTotalFornecedoresResponse> ServiceReference.ServicoFornecedores.RetornarQuantidadeTotalFornecedoresAsync(ServiceReference.RetornarQuantidadeTotalFornecedoresRequest request)
        {
            return base.Channel.RetornarQuantidadeTotalFornecedoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.RetornarQuantidadeTotalFornecedoresResponse> RetornarQuantidadeTotalFornecedoresAsync()
        {
            ServiceReference.RetornarQuantidadeTotalFornecedoresRequest inValue = new ServiceReference.RetornarQuantidadeTotalFornecedoresRequest();
            return ((ServiceReference.ServicoFornecedores)(this)).RetornarQuantidadeTotalFornecedoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.RetornarUsuariosResponse> ServiceReference.ServicoFornecedores.RetornarUsuariosAsync(ServiceReference.RetornarUsuariosRequest request)
        {
            return base.Channel.RetornarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.RetornarUsuariosResponse> RetornarUsuariosAsync(int quantidadePorPagina, int pagina)
        {
            ServiceReference.RetornarUsuariosRequest inValue = new ServiceReference.RetornarUsuariosRequest();
            inValue.quantidadePorPagina = quantidadePorPagina;
            inValue.pagina = pagina;
            return ((ServiceReference.ServicoFornecedores)(this)).RetornarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.RetornarUsuarioPorCNPJResponse> ServiceReference.ServicoFornecedores.RetornarUsuarioPorCNPJAsync(ServiceReference.RetornarUsuarioPorCNPJRequest request)
        {
            return base.Channel.RetornarUsuarioPorCNPJAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.RetornarUsuarioPorCNPJResponse> RetornarUsuarioPorCNPJAsync(string cnpj)
        {
            ServiceReference.RetornarUsuarioPorCNPJRequest inValue = new ServiceReference.RetornarUsuarioPorCNPJRequest();
            inValue.cnpj = cnpj;
            return ((ServiceReference.ServicoFornecedores)(this)).RetornarUsuarioPorCNPJAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.RetornarCRCPorCNPJResponse> ServiceReference.ServicoFornecedores.RetornarCRCPorCNPJAsync(ServiceReference.RetornarCRCPorCNPJRequest request)
        {
            return base.Channel.RetornarCRCPorCNPJAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.RetornarCRCPorCNPJResponse> RetornarCRCPorCNPJAsync(string cnpj)
        {
            ServiceReference.RetornarCRCPorCNPJRequest inValue = new ServiceReference.RetornarCRCPorCNPJRequest();
            inValue.cnpj = cnpj;
            return ((ServiceReference.ServicoFornecedores)(this)).RetornarCRCPorCNPJAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Domino))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Domino))
            {
                return new System.ServiceModel.EndpointAddress("http://recpabv1.redechesf.local/aplic/fornecedores.nsf/fornecedores?OpenWebServic" +
                        "e");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicoFornecedoresClient.GetBindingForEndpoint(EndpointConfiguration.Domino);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicoFornecedoresClient.GetEndpointAddress(EndpointConfiguration.Domino);
        }
        
        public enum EndpointConfiguration
        {
            
            Domino,
        }
    }
}
