image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - Compilação
  - Dockerização
  - Implantação

Construir e empacotar DLLs (qualidade):
  stage: Compilação
  before_script:
    - dotnet restore
  script: 
    - dotnet publish -c release -o ./Release --no-restore /p:Version="$(bash ./.ci/get-versao.sh 2>/dev/null)"
  artifacts: 
    paths:
      - Release/
  except:
    - tags

Construir e empacotar DLLs:
  stage: Compilação
  before_script:
    - dotnet restore
  script: 
    - dotnet publish -c release -o ./Release --no-restore /p:Version="$CI_COMMIT_TAG"
  artifacts: 
    paths:
      - Release/
  only:
    - tags

Dockerizar versão mais recente:
  image: docker
  services:
    - docker:dind
  stage: Dockerização
  script:
    - docker build -t harbor.chesf.gov.br/dgcds/compras:dev .
    - docker login -u $HARBOR_USER -p $HARBOR_PASSWORD harbor.chesf.gov.br
    - docker push harbor.chesf.gov.br/dgcds/compras:dev
  only:
    - develop
  dependencies:
    - Construir e empacotar DLLs (qualidade)

Dockerizar tag:
  image: docker
  stage: Dockerização
  services:
    - docker:dind
  script:
    - docker build -t harbor.chesf.gov.br/dgcds/compras:$CI_COMMIT_TAG .
    - docker login -u $HARBOR_USER -p $HARBOR_PASSWORD harbor.chesf.gov.br
    - docker push harbor.chesf.gov.br/dgcds/compras:$CI_COMMIT_TAG
  only:
    - tags
  dependencies:
    - Construir e empacotar DLLs

Implantar aplicação no Rancher:
  image: dirceusilva/base_k8s_python:latest
  stage: Implantação
  environment:
    name: qualidade
  script:
    - echo "${KUBE_CONFIG_DEV}" | base64 -d > /config
    - export KUBECONFIG=/config
    - git clone https://${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}@gitlab.com/chesf.gov.br/infra/devops/helm-charts.git
    - cat -A chart/answers_dev.yaml
    - yq -p=props chart/answers_dev.yaml | tr -d "'" > chart/values.yaml
    - cat chart/values.yaml
    - helm upgrade --force -i e-compras -n e-compras  helm-charts/charts/e-compras --reuse-values -f chart/values.yaml
  only:
    - develop
  dependencies:
    - Dockerizar versão mais recente

Requisitar implantação da infra:
  image: harbor.chesf.gov.br/dgcds/gitlab-mr-deploy
  stage: Implantação
  before_script:
    - configurar-git
  script:
    - sed -i "s/CI_COMMIT_TAG/$CI_COMMIT_TAG/g" ./chart/answers_hmg.yaml
    - sed -i "s/CI_COMMIT_TAG/$CI_COMMIT_TAG/g" ./chart/answers_prod.yaml
    - abrir-mr-deploy
  only:
    - tags
  dependencies:
    - Dockerizar tag